import Head from "next/head";
import { useEffect, useState } from "react";
import Navbar from "../layouts/Navbar";
import { useRouter } from "next/router";
import moment from "moment";

export default function Home() {
  const [posts, setPosts] = useState([]);
  const [loading, setLoading] = useState(true);
  const router = useRouter();

  function fetchData() {
    setLoading(true);
    fetch("https://mfidie.com/wp-json/wp/v2/posts")
      .then((response) => response.json())
      .then((data) => {
        setPosts(data);
        setLoading(false);
      });
  }

  useEffect(() => {
    fetchData();
  }, []);
  return (
    <div>
      <Head>
        <title>Mfidie - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <section className="text-gray-900 body-font">
        <div className="container px-5 py-12 mx-auto">
          <div className="block lg:flex lg:space-x-2  sm:px-4 px-2 py-12 mb-10">
            <div className="w-full lg:w-2/3">
              {loading ? (
                <div className="w-2/3 mx-auto">loading...</div>
              ) : (
                posts.length > 1 &&
                posts.slice(0, 3).map((post, index) => (
                  <a
                    key={index}
                    className="block rounded w-full lg:flex mb-10"
                    // href={`/${post.slug}`}
                    onClick={() => {
                      router.push({
                        pathname: `/${post.slug}`,
                        query: { id: post.id },
                      });
                    }}
                  >
                    <img
                      className="h-48 lg:w-48 flex-none bg-cover text-center overflow-hidden opacity-75"
                      src={post.jetpack_featured_media_url}
                    />
                    <div className="bg-white rounded px-4 py-4 flex flex-col justify-between leading-normal shadow">
                      <div>
                        <div className="mt-3 md:mt-0 text-gray-700 font-bold text-3xl mb-2">
                          {post.title.rendered}
                        </div>
                      </div>
                      <div className="flex mt-3">
                        {/* <img
                          alt=""
                          src="https://randomuser.me/api/portraits/men/11.jpg"
                          className="h-10 w-10 rounded-full mr-2 object-cover"
                        /> */}
                        <div>
                          {/* <p className="font-semibold text-gray-700 text-sm capitalize">
                            {" "}
                            eduard franz{" "}
                          </p> */}
                          <p className="text-gray-600 text-xs">
                            {moment(post.modified).format("MMM Do")}
                          </p>
                        </div>
                      </div>
                    </div>
                  </a>
                ))
              )}
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
